USE [DFNB3]
GO

/****** Object:  Table [dbo].[Nums]    Script Date: 4/16/2020 2:11:31 AM ******/
DROP TABLE [dbo].[Nums]
GO

/****** Object:  Table [dbo].[Nums]    Script Date: 4/16/2020 2:11:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Nums](
	[n] [int] NOT NULL,
 CONSTRAINT [PK_Nums] PRIMARY KEY CLUSTERED 
(
	[n] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


